### ISSUE TITLE
[NOMINATION][MAINTAINER]: arhimede, alexmerlin, MarioRadu, for maintaining laminas-api-tools

### ISSUE THREAD

**Issue by arhimede** [laminas/technical-steering-committee#135]
## Nomination

I'm nominating the following people to maintain laminas-api-tools:
 * arhimede      https://github.com/arhimede
 * alexmerlin    https://github.com/alexmerlin
 * MarioRadu     https://github.com/MarioRadu

As the discussion started in this PR https://github.com/laminas/technical-steering-committee/pull/134 , I would like to nominate a group of developers from DotKernel Organization in order to refactor and/or maintain laminas-api-tools and other new or current API related libraries.

- They have been working extensively with Laminas/Zend since Zend Framework 1.
- They have been contributing to various Zend Framework 1 libraries.
- Through their employment at Apidemia, they have been using Mezzio and Laminas tools from their inception, on a daily basis.
- They are up-to-date on API design best practices and guidelines.
- They have experience in understanding and satisfying the API requirements of clients through face-to-face interactions.
- They have an interest in fixing issues and implementing features, especially in the components which they use in their assigned projects, and are willing to invest time in doing so.

**Comment by internalsystemerror** [comment]
As discussed at the most recent TSC meeting (minutes not yet uploaded), the idea is a promising one and it was suggested that those nominated submit some PRs to the various `laminas`/`mezzio` repos. The intention with this is that it would:
- Allow us to get an impression of their work, and/or confirmation of their abilities
- Allow us to figure out a path forward on our side
- Allow those nominated to get accustomed with our processes (from GitHub Actions to Psalm Static Analysis)

After looking through the contribution history, I wasn't able to see anything outside of the `dotkernel` org, but if there are any could you mention this PR in those so we can track that here?

**Comment by arhimede** [comment]
@internalsystemerror @Ocramius 

Do you have any kind of guidance where to start with PR's ?

There are any specific issues or repos that need now fixes, new features and similar  ?

We need a starting point :-)

**Comment by internalsystemerror** [comment]
I know quite a few repos still need upgrading to psalm 5. We use renovate to bump dependencies, opening a PR if they don't upgrade cleanly, so you can look for PRs with the `renovate` label to see which upgrades needs some work still.

Here's a list of all open PRs across laminas for reference: https://github.com/pulls?q=is%3Aopen+is%3Apr+archived%3Afalse+user%3Alaminas+sort%3Acreated-asc+user%3Amezzio+user%3Alaminas-api-tools+

**Comment by alexmerlin** [comment]
Hey guys!
I'm Alex, one of the DotKernel developers recommended to you by @arhimede.
Just wanted to warm up with something light so I tried to make my first PR on [laminas/laminas-json-server](https://github.com/laminas/laminas-json-server) to fix some issues reported by Psalm.
I created my own branch and when I try to push my modifications, I get the following error:

> remote: Permission to laminas/laminas-json-server.git denied to alexmerlin.
> fatal: unable to access 'https://github.com/laminas/laminas-json-server.git/': The requested URL returned error: 403

Should we be able to make PRs without being members of the Laminas Organization?

**Comment by samsonasik** [comment]
@alexmerlin you can read the contributing guideline at https://github.com/laminas/.github/blob/main/CONTRIBUTING.md#recommended-workflow-for-contributions

**Comment by MarioRadu** [comment]
Hello there! 
My name is Mario and I'm the other developer from DotKernel recommended by @arhimede.
I've created a PR https://github.com/laminas/laminas-migration/pull/76 to fix some issues regarding Psalm checks.

**Comment by arhimede** [comment]
Me again .

My name is Julian, @arhimede , and i am from Dotkernel organisation.

I have created a PR https://github.com/laminas/laminas-paginator/pull/56 mostly to try the deployment process , also to fix Psalm checks.

**Comment by arhimede** [comment]
@alexmerlin @MarioRadu this issue is not actual anymore , since laminas api tools are in security-only mode.
Let's open an separate issue for each of you , and do a separate PR in a repository that is marked as active, 
either in Mezzio or Components column from the status page 
https://getlaminas.org/packages-maintenance-status/
