### ISSUE TITLE
[NOMINATION][TSC] Julian Somesan

### ISSUE THREAD

**Issue by weierophinney** [laminas/technical-steering-committee#177]
I would like to nominate [Julian Somesan](https://github.com/arhimede) to join the Technical Steering Committee.

Julian has been an active member of our Slack and Discourse, providing helpful information to users. Additionally, he has formed a company, [Apidemia](https://www.apidemia.com), that is writing tools and products that build on top of Laminas and Mezzio components, including dotKernel API. I feel he would provide a much-needed viewpoint for the TSC as a business owner, and could help drive some marketing and awareness efforts for the project.

**Comment by akrabat** [comment]
Not sure what processes there are, but a +1 from me.

Regards,

Rob

**Comment by samsonasik** [comment]
+1

**Comment by geerteltink** [comment]
+1

**Comment by asgrim** [comment]
+1

**Comment by froschdesign** [comment]
In the past, we have held a vote on this during the meeting. We should therefore do the same again.

**Comment by arhimede** [comment]
@froschdesign but if again at the next meeting  will not be quorum, the vote will be useless. 
The TSC minute from May meeting is still not approved nor rejected.

See also the @gsteel agenda for July meeting, things need to be moved in terms of decision process. 

I think this nomination can be discussed here too.

**Comment by froschdesign** [comment]
A vote was held in the past because this also ensured anonymity and abstention.

**Comment by froschdesign** [comment]
In a vote, abstaining or voting against also means that you took part in the vote. We do not know this here. (This is also a point that @gsteel has put on the agenda – inactive members.)

> I only want to move things forward , that's all.

👍🏻

**Comment by arhimede** [comment]
Well, we do know here, actually.
Right now there are 8 votes Pro ( including @weierophinney who opened the issue )
