### ISSUE TITLE
[NOMINATION][MAINTAINER]: Filippo Tessarotto – @Slamdunk for laminas-mail

### ISSUE THREAD

**Issue by froschdesign** [laminas/technical-steering-committee#58]
## Nomination

[Filippo Tessarotto – @slamdunk](https://github.com/Slamdunk) has been involved in the Laminas / Zend Framework ecosystem since version 1 of the framework and additionally he is actively involved in different projects like ParaTest, PSR-7 Storage-less HTTP Sessions, lcobucci/jwt and some more.
He is already doing the work expected of a maintainer in terms of quality, design decisions and testing.

Therefore I nominate @Slamdunk as a maintainer for laminas-mail.

**Comment by weierophinney** [comment]
The TSC completed a vote on 2021-02-09, and approved the nomination. @slamdunk has been added as a maintainer on the laminas-mail repository.
