### ISSUE TITLE
RFC: We need a mail provider

### ISSUE THREAD

**Issue by weierophinney** [laminas/technical-steering-committee#69]
Q | A
- | -
RFC | Yes

I've been taking care of domain registration fees since before we launched. The provider I use for getlaminas.org allows me to create one email forwarding address as part of the fee, but that's the limit; beyond that, and it's $1 or $2 per month per address. So far, we've only had to use one (security@getlaminas.org), but with the upcoming commercial vendor/support provider program, we will need another so that we can receive logos and receipts from these supporters. Additionally, it will give us a channel to communicate with them going forwards.

I've done some research into mail providers, and these are the top contenders, in no particular order:

Provider | Cost (if known) | Features/Comments
--------- | ---------------- | -----------------
Gmail | $6/month/user | We all know this one.
Groups.io | $20/month | It's more of a group collab option; I'm not 100% sure it can _accept_ email for a domain; if it can, that would be in the $200/month enterprise option (we can likely get a 50% discount on both plans as we are LF members, though)
Protonmail | 5EUR/month | Highly secure, but we'd be limited to 5 addresses, and no "catch-all" email for the domain.
Zoho | $1/month/user | There is a free tier that accomodates up to 5 addresses, but also disables SMTP and IMAP support.

We appear to have around a dozen people currently donating $10 or more monthly, and have accumlated several thousand dollars in our account, so we have funds; that said, I think we'd all rather go cheap on things like infrastructure so that we can get to a point where we can either fund targeted projects or part-time personnel.

My inclination is to go with the Zoho paid plan, and start with 2 addresses (our security address, and a general catch-all address); having the paid plan gets us IMAP and SMTP, which in turn ensures nobody needs to actively check so long as they have an email client subscribing to the addresses. I doubt we'll need more than a handful of addresses unless we decide we want the entire TSC and/or all maintainers to have getlaminas.org addresses; if that happens, we can revisit the decision.

**Comment by rieschl** [comment]
Hmm I don't know if I really understood your needs, but in Austria/Germany/Europe you'll basically get "free" basic email with every web hosting package. Eg: https://www.hetzner.com/webhosting/
Level 1: basic web hosting plus 100 email accounts for 1,93€/month
🤷‍♂️

**Comment by weierophinney** [comment]
@rieschl We don't have a standard web hosting plan; Platform.sh (which is a PaaS provider) sponsors a few sites for us (getlaminas.org, laminas.dev, api-tools.getlaminas.org), and the rest is on github pages. The domain provider I'm using (Hover) charges per email address, and only provides webmail. As such, your suggestion doesn't really apply to our current scenario.

**Comment by rieschl** [comment]
you don't _have_ to use the hosting, your can point the DNS records everywhere you want. but I think the domain has to be registered/transferred to them.

**Comment by mbourquin** [comment]
@weierophinney, look over here: https://www.infomaniak.com/en/hosting/web-and-mail/mail-hosting They have an excellent infrastructure, console, tools and the prices are correct. You can subscribe to the email service only without hosting. For 5 emails it costs about 30 dollars per year. (5 emails is the minimum)

**Comment by froschdesign** [comment]
> and no "catch-all" email for the domain.

Is the "catch-all" feature relevant?

**Comment by weierophinney** [comment]
> Is the "catch-all" feature relevant?

It's useful so that we can publish additional addresses as needed, but have them all route to a catch-all mailbox.

**Comment by ghostwriter** [comment]
`Protonmail` has a "catch-all" feature.

> Catch-All is currently only available for **Visionary** and **Professional** ProtonMail account holders.

See: https://protonmail.com/support/knowledge-base/catch-all/
See: https://protonmail.com/signup

Price: 
- Visionary @ `€24.00 /Month`
- Professional @ `€6.25 /Month/User`

`* pricing may or may not vary depending on your location.`

**Comment by bcremer** [comment]
I can also recommend Fastmail as an email provider with good IMAP and STMP support.

https://www.fastmail.com/pricing/

Pricing is $5 / user / month for the Standard plan that offers custom domains and catch-all addresses.

**Comment by heiglandreas** [comment]
I can only again toss Gandi into the ring: https://www.gandi.net/en-US/domain/email

When hosting our DNS with them we can get rather cheap email along with decent DNS. And I do know that they are also open for sponsoring OSS software. At least were in the past.

**Comment by geerteltink** [comment]
https://www.namecheap.com/hosting/email/

15$ / year.
10 aliases.
SMTP/IMAP
Catch all.

Or use namecheap for your DNS management and you get free email forwarding.

**Comment by weierophinney** [comment]
This may not be an issue at this point.

The Linux Foundation has been able to setup aliases, including some that resolve to multiple addresses, and my primary contact there (John Mertic) has now requested that I get access to the project control panel so that I don't need to go through their support system to set them up or make DNS changes. :tada:

**Comment by heiglandreas** [comment]
Short question regarding the part 

> I've been taking care of domain registration fees since before we launched.

Is this by now covered by our funding?

**Comment by weierophinney** [comment]
@heiglandreas Actually, transferred all DNS to the Linux Foundation earlier this year, and they take care of it for us now. :smile:

I'm still taking care of GreetBot... but that service is going EOL in a few weeks.

**Comment by heiglandreas** [comment]
Can be closed
