### ISSUE TITLE
[NOMINATION][MAINTAINER]: MassiCav, clarphp, slaff-at-zend, for maintaining laminas-db

### ISSUE THREAD

**Issue by weierophinney** [laminas/technical-steering-committee#73]
## Nomination

I nominate the following people to maintain [laminas-db](https://github.com/laminas/laminas-db):

- [Massi Cavicchioli (@MassiCav)](https://github.com/MassiCav)
- [Clark Everetts (@clarkphp)](https://github.com/clarkphp)
- [Slavey Karadzhov (@slaff-at-zend)](https://github.com/slaff-at-zend)
- myself

Each of these individuals do regular client-facing work through their employment at Zend by Perforce that requires experience and expertise with a variety of RDBMS platforms, including the various enterprise-facing RDBMS platforms supported by laminas-db (e.g., DB2, OCI8). Each also has a track-record of high-quality code, and I will be available to train them in Laminas QA standards. They have a vested interest in ensuring that fixes and features continue to move forward in the component, due to their customer list, and are willing to invest time in doing so.

**Comment by Ocramius** [comment]
Heyo,

I'm very much on-board with @MassiCav, @clarkphp and @slaff-at-zend taking over maintenance, but if it would be them individually (and officially) being the maintainers, not Perforce.

**Comment by weierophinney** [comment]
Yeah - the plan is to add them as individual maintainers to the project, and if we identify others on the team who could contribute, either we would review their PRs, or we would nominate them to be additional maintainers. I mentioned Perforce as we all work together, and we came up with the maintenance plan together.

**Comment by boesing** [comment]
Closing this as we voted on it on [2021-05-03](https://github.com/laminas/technical-steering-committee/blob/main/meetings/minutes/2021-05-03-TSC-Minutes.md#laminas-db-maintainer-vote)
